### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by notapplicableio** [MindscapeHQ/raygun4apple#50]
Are there any plans to support visionOS? Currently, packages that depend on raygun4Apple cannot compile.

**Comment by sumitramanga** [comment]
Hi @notapplicableio, currently there are no plans at this stage as it usually will depend on demand. 

This also relates to https://github.com/MindscapeHQ/raygun4apple/issues/49
This provider overhaul change will need to be made to the provider in order to support visionOS. 

Please feel free to raise this over in our forums - Our Product team can look into this and see where can fit in :) 

For now, I will close this thread. If there is nothing raised over in our forums, I can go ahead and do so. So that we don't forget 

Kind regards,
Sumitra
